Updates example
arturoc/ofxEasing pull request #2
Opened 2017-04-20 16:28 UTC by javl

Small update to the example; adds a simple animation underneath each of
the plots showing the different easing effects.

2017-04-20 16:55 UTC, arturoc requested changes
Can you post a screenshot to understand what it does? I've also added a comment

2017-04-20 16:55 UTC, arturoc commented on example_plots/src/ofApp.cpp
> +	ofBackground(255);
It's preferred to use ofSetBackgroundColor now

2017-04-20 20:44 UTC, javl commented
I've changed `ofBackground` to `ofSetBackgroundColor`

The update adds a small animated rectangle underneath each plot, showing its easing behavior (moves in 3 seconds, waits for 1, then restarts movement).


![unnamed window_340](https://cloud.githubusercontent.com/assets/734644/25251758/b1fffe8a-261a-11e7-8c85-18047e1a6433.png)

2017-04-22 14:46 UTC, arturoc commented
that looks great thanks!

2017-04-22 14:46 UTC, merged